// THIS FILE IS GENERATED BY scripts/generate-widget-map.mjs
// DO NOT EDIT BY HAND. Run `npm run prebuild` (or `node scripts/generate-widget-map.mjs`) to refresh.
// Source of truth: widget_catalog table (P9 data-driven).

import { lazy } from 'react';
import type { LazyExoticComponent, ComponentType } from 'react';

const generic_placeholder = lazy(() => import('./types/generic-placeholder'));
const custom_career_path = lazy(() => import('./types/custom-career-path'));
const kpi_number_card = lazy(() => import('./types/kpi-number-card'));
const kpi_ring_widget = lazy(() => import('./types/kpi-ring-widget'));
const leave_balance_card = lazy(() => import('./types/leave-balance-card'));
const custom_my_card = lazy(() => import('./types/custom-my-card'));
const list_widget = lazy(() => import('./types/list-widget'));
const feed_widget = lazy(() => import('./types/feed-widget'));
const pending_approvals_card = lazy(() => import('./types/pending-approvals-card'));
const shortcut_widget = lazy(() => import('./types/shortcut-widget'));

export const widgetMap: Record<string, LazyExoticComponent<ComponentType<{ code: string }>>> = {
  active_users_kpi: generic_placeholder,
  ai_assistant: generic_placeholder,
  api_usage: generic_placeholder,
  calendar_view: generic_placeholder,
  career_path: custom_career_path,
  compensation_bands: generic_placeholder,
  compliance_status: generic_placeholder,
  engagement_score: kpi_number_card,
  headcount_kpi: kpi_number_card,
  learning_progress: kpi_ring_widget,
  leave_balance: leave_balance_card,
  my_card: custom_my_card,
  my_documents: list_widget,
  my_tasks: list_widget,
  notifications_feed: feed_widget,
  open_positions_kpi: kpi_number_card,
  org_chart_mini: generic_placeholder,
  pending_approvals: pending_approvals_card,
  performance_scores: kpi_number_card,
  process_health: generic_placeholder,
  quick_links: shortcut_widget,
  skill_gaps_chart: generic_placeholder,
  system_health: generic_placeholder,
  team_absences: generic_placeholder,
  time_tracking: generic_placeholder,
  turnover_kpi: generic_placeholder,
};
